# Site settings
title: cassidy.codes
name: Cassidy K
email: hello@cassidy.codes
url: http://cassidy.codes
description: >
  Cassidy K is a Ruby on Rails developer and project manager from Toronto, Canada.

# Build settings

plugins: [jekyll-paginate]

kramdown:
  input: GFM
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
paginate: 10
paginate_path: "/blog/page:num/"
